name: sbt-test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        java: [ 'adopt@1.8', 'adopt@1.11' ]
        scala: [ '2.12.10', '2.11.12', '2.13.6']

    steps:
    - uses: actions/checkout@v2
    - name: Setup Scala and Java
      uses: olafurpg/setup-scala@v10
      with:
        java-version: ${{ matrix.java }}
    - name: Cache scala dependencies
      uses: coursier/cache-action@v6
    - name: Run tests
      run: sbt ++${{ matrix.scala }} test
